# Reproducable results with keras

Because of random initialization we may get different result by running the models each time. 
- Python
- Numpy
- TensorFlow

we have to set random seed for each of these

In [ ]:
import numpy as np
import tensorflow as tf
import random as rn

In [ ]:
import os
os.environ['PYTHONHASGSEED'] = '0'
os.environ['CUDA_VISIBLE_DEVICES'] = ''  # forcing the code to run on cpu
# this is necessary for any hash based algorithm.

In [ ]:
# setting the seed for numpy
np.random.seed(123) # we can use any integer number 

In [ ]:
# setting the seed for python random numbers
rn.seed(123)

In [ ]:
# setting the seed for tensorflow
tf.random.set_seed(1234)

# Initialize and access Bias

In [1]:
import keras 
from keras.models import Sequential
from keras.layers import Dense, Activation

In [2]:
model = Sequential([
                    Dense(4, input_shape = (1,), activation='relu', use_bias=True, bias_initializer='zeros'), # we can use xavier initializer
                    Dense(2, activation='softmax')
])
# by_default use_bias is true

In [3]:
model.get_weights()

[array([[-1.0908242 ,  0.81720734,  0.6380968 ,  0.8452325 ]],
       dtype=float32),
 array([0., 0., 0., 0.], dtype=float32),
 array([[-0.9331958 , -0.4608717 ],
        [ 0.47720933, -0.40190744],
        [ 0.79337525, -0.2518444 ],
        [ 0.94572186,  0.16292667]], dtype=float32),
 array([0., 0.], dtype=float32)]

In [ ]:
print(help(Dense))

# Learnable Parameters